### ISSUE TITLE
Disable Alt-SEO blueprint fields being auto added to every collection

### ISSUE THREAD

**Issue by unmaskz** [alt-design/Alt-SEO-Addon#16]
Hey,
Love the add-on really good, only question would be if it was possible to disable the alt-seo fields/blueprint being added to every collection. Only need it on Pages collection for example.

**Comment by benmAltDesign** [comment]
Hi there. 
Glad to hear you're enjoying the addon. What I've done is I've added a supported field for the settings.yaml named "alt_seo_asset_container_include".

This is used for explicit inclusion of collections that you want to augment. If It's set to null or omitted from the file entirely, all collections will be augmented. However if you populate it with an array as picture, only these collections will be augmented.

![image](https://github.com/alt-design/Alt-SEO-Addon/assets/149595159/9a5e0973-58ef-4d39-98c3-9a0d15dbcaae)

Hope this fits your needs when we do the next release.

Thanks

**Comment by bjo3rnf** [comment]
Hi,

sorry for resurrecting the issue but how does this setting apply to Statamic 5? AFAIK there is no (more) settings.yaml.

Thanks for your great addon.

Cheers
Björn
