### ISSUE TITLE
Question about `alt_seo_meta_url`

### ISSUE THREAD

**Issue by ceesvanegmond** [alt-design/Alt-SEO-Addon#22]
Hi,

I've noticing that in AltSeo.php https://github.com/alt-design/Alt-SEO-Addon/blob/main/src/Tags/AltSeo.php#L131C42-L131C58 the field `alt_seo_meta_url` is used. However this field is nowhere to be found. Nor in settings.yaml nor in other config.

Because the field is't found `ENV('APP_URL');` is always returned in this `getUrl()` function.
Is there a reason for this? Basically always the homepage is displayed in `og:url`. Shouldn't `alt_seo_meta_url` be the `alt_seo_canonical_url` instead?

Thanks!

**Comment by Alt-Ben** [comment]
Hey! 

Just released the package, v5 compatible and the above has been changed.

Let me know if it's all okay for you guys!

Cheers!

Ben
