### ISSUE TITLE
Configuration of alternative asset container names

### ISSUE THREAD

**Issue by sandro-imhof** [alt-design/Alt-SEO-Addon#3]
After installing this addon in one of my projects, I got the error message `Asset Container [assets] not found`. Turns out the problem was the name of my asset container and after fixing this it works fine.

Now my question is if there are any plans for a config file or any other means of configuration for alternative asset container names? Since I work on projects with multiple differently named asset controllers, this would help a lot

**Comment by Alt-Ben** [comment]
Hey Sandro!

Thanks for the suggestion - we've actually just added this into the latest release - hopefully it works okay for you!
